name: flutter_richtext_composer
description: A Flutter package for composing rich text in a i18n friendly way
version: 0.2.0
homepage: https://github.com/rockerhieu/flutter_richtext_composer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
